import { chromium } from "playwright";
const browser = await chromium.launch({ args: ["--no-sandbox"] });
const page = await browser.newPage({ viewport: { width: 390, height: 844 } });
const errors = [];
page.on("pageerror", (e) => errors.push(e.message));
page.on("console", (m) => { if (m.type() === "error") errors.push(m.text()); });
await page.goto("http://127.0.0.1:8080/", { waitUntil: "networkidle" });
await page.screenshot({ path: "/workspace/screenshots/title-mobile.png", fullPage: true });
await page.getByRole("button", { name: "Start hopping" }).click();
await page.waitForTimeout(400);
await page.screenshot({ path: "/workspace/screenshots/decades-mobile.png", fullPage: true });
await page.getByRole("button", { name: /The First Pair/ }).click();
await page.waitForTimeout(1800);
await page.screenshot({ path: "/workspace/screenshots/play-mobile.png" });
console.log("overflowX", await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth));
console.log("errors", errors);
await browser.close();
