import { chromium } from 'playwright';
const browser = await chromium.launch({ args: ['--no-sandbox'] });
const page = await browser.newPage({ viewport: { width: 1280, height: 800 } });
page.on('pageerror', e => console.log('PAGEERROR', e.message));
page.on('console', m => { if (m.type()==='error') console.log('CONSOLE', m.text()); });
await page.goto('http://127.0.0.1:8080/', { waitUntil: 'networkidle' });
await page.getByRole('button', { name: /start walking/i }).click();
await page.waitForTimeout(600);
await page.screenshot({ path: '/workspace/screenshots/decades-rebrand.png', fullPage: true });
console.log('select text', (await page.locator('h2').first().innerText()));
await page.getByRole('button', { name: /the first pair/i }).click();
await page.waitForTimeout(1800);
const canvas = await page.locator('canvas').count();
console.log('canvas', canvas);
await page.screenshot({ path: '/workspace/screenshots/play-rebrand.png' });
await page.mouse.down();
await page.waitForTimeout(700);
await page.screenshot({ path: '/workspace/screenshots/play-charge.png' });
await page.mouse.up();
await page.waitForTimeout(1400);
await page.screenshot({ path: '/workspace/screenshots/play-after.png' });
const mobile = await browser.newPage({ viewport: { width: 390, height: 844 } });
await mobile.goto('http://127.0.0.1:8080/', { waitUntil: 'networkidle' });
await mobile.screenshot({ path: '/workspace/screenshots/title-mobile-rebrand.png', fullPage: true });
await browser.close();
console.log('done');
